name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:s3-latest
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: CI=false bun test
      # - run: bun run build
      # - run: |
      #     echo '@ricsam:registry=https://registry.npmjs.org' >> .npmrc
      #     echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      #     echo '//registry.npmjs.org/:always-auth=true' >> .npmrc
      # - name: changeset publish
      #   run: npx changeset publish --access=public --registry=https://registry.npmjs.org/
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
